version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: t2d-project
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgresData

volumes:
  postgres_data:
